---
- name: MariaDB
  hosts: svdebian
  gather_facts: true
  become: true
  remote_user: spt
  vars:
    mysql_root_password: "abc123."
  tasks:
    - name: Instalar
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Iniciar
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Contraseña root
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
