---
- name: MariaDB
  hosts: svdebian
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "abc123."
  tasks:
    - name: Instalar
      apt:
        name:
          - mariadb-server
          - python3-PyMySQL
        state: latest

    - name: Iniciar
      service:
        name: mariadb
        enabled: true
        state: started
