---
- name: Instalar colección community.mysql
  hosts: localhost
  tasks:
    - name: Instalar
      ansible.builtin.collection:
        name: community.mysql

- name: MariaDB
  hosts: svdebian
  gather_facts: true
  become: true
  remote_user: spt
  vars:
    mysql_root_password: "abc123."
  tasks:
    - name: Instalar
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Iniciar servicio
      service:
        name: mariadb
        enabled: true
        state: started

    - name: Generar contraseña de root
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host_all: true
      
