---
- name: Instalar MariaDB
  hosts: svdebian
  gather_facts: yes
  become: yes
  remote_user: spt
  vars:
    mysql_root_password: "abc123."
  tasks:
  
    - name: Instalar 
      apt:
        name:
          - mariadb-server
        state: latest
        
    - name: Iniciar
      service:
        name: mariadb
        enable: yes
        state: started

    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: yes
        password: "{{ mysql_root_password }}"
        host: localhost

    - name: Eliminar root remoto 
      mysql_user:
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent
