---
- name: "Actualizar apt"
  hosts: debian
  become: yes
  remote_user: spt
  tasks:
    - name: "Actualizar todas las máquinas Debian/Ubuntu"
      apt:
        update_cache: yes
        upgrade: dist
        
- name: "Actualizar dnf"
  hosts: fedora
  become: yes
  remote_user: root
  tasks:
    - name: "Actualizar todas las máquinas Red Hat/Fedora"
      dnf:
        name: '*'
        state: latest
    
    - name: "Mejorar todas las máquinas Red Hat/Fedora"
      command: dnf upgrade --refresh
