---
- name: MariaDB
  hosts: svdebian
  gather_facts: yes
  become: yes
  remote_user: spt
  vars:
    mysql_root_password: "abc123."
  tasks:
    - name: Instalar
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Iniciar servicio
      service:
        name: mariadb
        enabled: yes
        state: started
...
    - name: Generar contraseña de root
      community.mysql.mysql_user:
        check_amplicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: localhost
        state: absent

    - name: Borrar root remoto
      community.mysql.mysql_user:
        check_implicit_admin: yes
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        host: localhost
        state: absent
       
