---
- name: MariaDB
  hosts: svdebian
  gather_facts: yes
  become: yes
  remote_user: spt
  tasks:
  
    - name: Instalar
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Iniciar servicio
      service:
        name: mariadb
        enabled: yes
        state: started
        
    - name: Generar contraseña de root
      command: /usr/bin/mysqladmin -u root password "abc123."
      ignore_errors: yes

    - name: Eliminar root acceso remoto
      community.mysql.mysql_user:
        login_user: root
        login_password: abc123.
        name: root
        host_all: yes
        state: absent
