---
- name: MariaDB
  hosts: svdebian
  gather_facts: yes
  become: yes
  remote_user: spt
  tasks:
  
    - name: Instalar Python
      raw: apt-get update -y && apt-get install -y sudo software-properties-common python3-pip
      changed_when: false

    - name: Crear ruta para dependencias
      command: mkdir ~/venv
      
    - name: Instalar dependencias
      apt:
        name:
          - python3-venv
          - python3-pip
        state: present

    - name: Activar dependencias
      shell: |
        python3 -m venv ~/venv
        source ~/venv//bin/activate
        pip install PyMySQL mysqlclient
      args:
        executable: /bin/bash
      
    - name: Instalar mariaDB
      apt:
        name:
          - mariadb-server
        state: latest

    - name: Iniciar servicio
      service:
        name: mariadb
        enabled: yes
        state: started
        
    - name: Generar contraseña de root
      command: /usr/bin/mysqladmin -u root password "abc123."
      ignore_errors: yes

    - name: Eliminar root acceso remoto
      community.mysql.mysql_user:
        login_user: root
        login_password: abc123.
        name: root
        host_all: yes
        state: absent
