---
- name: "Configurar servidores MariaDB"
  hosts: svdebian
  become: yes
  tasks:
    - name: "Instalar MariaDB"
      apt:
        name: mariadb-server
        state: present

    - name: "Confirmar instalación"
      mysql_secure_installation:
        login_password: ''
        login_unix_socket: /var/run/mysqld/mysqld.sock
        new_password: 'abcd1234.'
        user: root
        change_root_password: yes
        remove_anonymous_user: yes
        remove_test_database: yes
        disallow_root_login_remotely: yes

    - name: "Crear base de datos"
      mysql_db:
        name: awx_db
        state: present
        encoding: utf8
        collation: utf8_general_ci

    - name: "Crear usuario con privilegios"
      mysql_user:
        name: user_db
        password: 'abc123.'
        priv: 'awx_db.*:ALL'
        state: present
